---
apiVersion: v1
kind: Pod
metadata:
  name: activity2
spec:
  containers:
    - image: nginx:1.23
      name: nginx-container
      ports:
        - containerPort: 80
          protocol: TCP
    - image: jenkins/jenkin
      name: jenkins-container
      ports: 
        - containerPort: 8080
          protocol: TCP      