---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-clusterip
spec:
  selector:
    app: nginx
    version: "1.0"
  type: ClusterIP
  ports:
    - name: web-port
      port: 32000
      targetPort: 80
