---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: jenkins-rs
labels:
  app: jenkins
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins-rs
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:lts-jdk11
          name: jenkins-container
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests: 
              memory: "128mi"
            limits:
              memory: "512mi"
      

     