apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector: 
    app: nginx
    version: "1.0"
  type: ClusterIP
  ports:
    - name: web-port
      port: 36000
      targetPort: 80
      protocol: TCP