apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector: 
    app: nginx
    version: "1.0"
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32000
      targetPort: 80
      