---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-labels
  labels:
    app: nginx
    version: "1.23"
spec:
  containers:
    - image: nginx:1.23
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP