---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
  labels:
        app: nginx
        version: "1.23"
spec:
  selector:
    matchLabels: 
      app: nginx
  replicas: 5
  minReadySeconds: 3
  template:
    metadata: 
      name: rc-nginx
    spec:
      containers:
        - image: nginx:1.23
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP 
