---
apiVersion: v1
kind: Pod
metadata: 
  name: probes
spec:
  containers:
    - image: nginx:1.23
      name: nginx
      ports: 
        - containerPort: 80
          protocol: TCP
  livenessProbe: 
    tcpSocket:
      port: 80
  readinessProbe:
    httpGet: 
      port: port
