---
apiVersion: v1
kind: Pod
metadata: 
  init-containers
spec: 
  initContainers:
    - image: alpine:3
      name: init-container1
      command:
        - sleep
        - "30"
    - image: alpine:3
      name: init-container2
      command:
        - sleep
        - "30"
  containers:
    - image: nginx:1.23
      name: nginx-container
      ports:
        - containerPort: 80
          protocol: TCP
