---
apiVersion: v1
kind: Pod
metadata:
  name: restart-demo
spec:
  restartPolicy: Never
  containers:
    - image: alpine:3
      name: alpine-container
      command:
        - sleep

---

kind: Pod
metadata:
  name: restart-demo
spec:
  restartPolicy: Always
  containers:
    - image: alpine:3
      name: alpine-container2
      command:
        - sleep
        - "3"
